### ISSUE TITLE
Conceal API key

### ISSUE THREAD

**Issue by LaurentBaj** [screentek/Optimizely#10]
Hi! 

I am working on a Optimizely project we're we need to integrate ImageShop without displaying the token in appsettings.json. I know that it is possible, with Azure Key Vault, to add a reference to the keys in keyvault, but we are not using Azure Key Vault.

Is there a way to override this? 

```
"ImageshopOptimizelyPlugin": {
    "Settings": {
        "token": "<api key>"
    }
}
```

**Comment by LucGosso** [comment]
we have added Added  AddEnvironmentVariables to version 1.2.5
