### ISSUE TITLE
TinyMCE image-data no longer works

### ISSUE THREAD

**Issue by Niiilsen** [screentek/Optimizely#15]
**Missing image-data**
In version 1.2.6, adding an image in tinyMCE no longer adds alt-text, description etc, the only thing being injected is the img-tag and width. Downgrading to 1.2.2 solved the issue so it seems to be a bug with v 1.2.5+.

**Comment by LucGosso** [comment]
it really should, here is the code which is runing: https://github.com/screentek/Optimizely/blob/release/1.2.6/src/TinyMce/ClientResources/ViewFiles/InsertImage.cshtml#L171 

Can you check again, if you can debug in console?

**Comment by Niiilsen** [comment]
The Imageshop result log shows all the correct data:

`Imageshop result: {"code":"EID-03412","image":{"file":"https://v.imgi.no/emz8byueam","width":400,"height":0,"thumbnail":"https://magik.imageshop.no/iMageWithFallbackAndMagikAndS3.aspx?d=1&t=638744256000000000&c=image%2fjpeg&base=496&h=8D332451CB904FC479A724CF791F86BD&x=0&y=0&real=&img=6922ff97-ebf9-48a5-a1a6-49a166234cea-v-4.jpg"},"text":{"no":{"title":"IoT stock","description":"iStock bilde som kan benyttes på trykte materiale","rights":"","credits":"","tags":"","altText":"En hånd som holder en AI jordklode","categories":[],"documentinfo":[{"DocumentInfoTypeId":463,"Name":"Alternativ tekst","Value":"En hånd som holder en AI jordklode"}]},"en":{"title":"","description":"","rights":"","credits":"","tags":"","altText":null,"categories":[],"documentinfo":[{"DocumentInfoTypeId":464,"Name":"Alternative text","Value":null}]},"sv":{"title":null,"description":null,"rights":null,"credits":null,"tags":null,"altText":null,"categories":null,"documentinfo":null},"nb":{"title":"IoT stock","description":"iStock bilde som kan benyttes på trykte materiale","rights":"","credits":"","tags":"","altText":"En hånd som holder en AI jordklode","categories":[],"documentinfo":[{"DocumentInfoTypeId":463,"Name":"Alternativ tekst","Value":"En hånd som holder en AI jordklode"}]},"nn":{"title":"IoT stock","description":"iStock bilde som kan benyttes på trykte materiale","rights":"","credits":"","tags":"","altText":"En hånd som holder en AI jordklode","categories":[],"documentinfo":[{"DocumentInfoTypeId":463,"Name":"Alternativ tekst","Value":"En hånd som holder en AI jordklode"}]},"da":{"title":null,"description":null,"rights":null,"credits":null,"tags":null,"altText":null,"categories":null,"documentinfo":null}},"extraInfo":null,"documentId":6866742,"AuthorName":null,"InterfaceList":[{"InterfaceID":1444147,"InterfaceName":"Kommunikasjon konsern"}],"profile":null,"focalPoint":{"x":0.58400000000000007,"y":0.021352313167259829}};;400;0;null;{"Name":"IoT stock","Description":"iStock bilde som kan benyttes på trykte materiale","Credits":"","Created":"/Date(-62135596800000)/","AuthorName":null,"Tags":""}`

Since i only get undefined for the currentImage-logging i cant really tell if the object is correctly structured before it is inserted.
ref: [Issue #16](https://github.com/screentek/Optimizely/issues/16)  

However the output is as follows:
`<img src="https://v.imgi.no/emz8byueam" width="400">`

**Comment by LucGosso** [comment]
what is the iframe url to insertimage? 

the lang parameter should match the "text": {"no" .. "en": in image json, what lang do you use on the page context? 

is it working if you work in english or no?

**Comment by Niiilsen** [comment]
No, it doesn't work with either english or norwegian.

I'm not sure what url you're asking so here's all of them!
**Cms:**
`https://mydomain.no/EPiServer/CMS/?language=no#context=epi.cms.contentdata:///5544&viewsetting=viewlanguage:///no`
(if this is the url being used then it fails because of the query param "language" instead of "lang")

**Iframes**
`<iframe src="https://mydomain.no/imageshoptinymce/insertimage/?TINYMCE=true&amp;TINYMCEEXTENDED=true&amp;CULTURE=nb-no&amp;IMAGESHOPLANGUAGE=no&amp;image=undefined&amp;image=undefined" data-alloy-tabstop="true" tabindex="-1"></iframe>`

`<iframe id="MyFrame" src="https://client.imageshop.no/InsertImage2.aspx?TINYMCE=true&amp;TINYMCEEXTENDED=true&amp;CULTURE=nb-no&amp;IMAGESHOPLANGUAGE=no&amp;image=undefined&amp;image=undefined&amp;IFRAMEINSERT=true&amp;IMAGESHOPTOKEN=9x5I5PIsG91qYiFgEk6meofgpVR5tQlYOfd3a4pidHcsTQPgZc&amp;SHOWSIZEDIALOGUE=true&amp;SHOWCROPDIALOGUE=true&amp;FREECROP=true&amp;IMAGESHOPINTERFACENAME=&amp;IMAGESHOPDOCUMENTPREFIX=Warning&amp;IMAGESHOPSIZES=&amp;FORMAT=json" style="height: 558px; width: 1198px;"></body></html></iframe>`

**Comment by LucGosso** [comment]
okay, i found an error in code, will need to fix the errors and republish the package... how in the hurry are you?

**Comment by Niiilsen** [comment]
No immediate hurry, we'll just stick with 1.2.2 until it's fixed.
Would be nice to get an ETA on when it will be done though.

**Comment by LucGosso** [comment]
Please verify the newest version https://nuget.optimizely.com/package/?id=Imageshop.Optimizely.Plugin&v=1.2.6.2

**Comment by Niiilsen** [comment]
Issue is fixed in 1.2.6.2!
