### ISSUE TITLE
Configurations are only loaded from appsettings.config

### ISSUE THREAD

**Issue by Goaral** [screentek/Optimizely#2]
When running this locally with appsettings.development.config it still required the token to be in appsettings.json 
https://github.com/screentek/Optimizely/blame/master/src/Configuration/ImageshopConfigurationSection.cs#L21

Should be loaded from Configuration.GetSection("GetaEpiImageshop:Settings:token");

**Comment by respiant** [comment]
Hi, thanks for letting us know. I will look into this and keep you updated when a fix is ready.

**Comment by respiant** [comment]
@Goaral 
This has now been solved in the newest update of the plugin, version 1.0.41.
You can check it out here: https://www.nuget.org/packages/Imageshop.Optimizely.Plugin.

Let me know if you still have issues.
